name: treehole_app
description: 匿名树洞 App MVP
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2 # 定位核心插件
  permission_handler: ^10.2.0 # 权限管理
  emoji_picker_flutter: ^2.0.12 #表情
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/